version: "3.3"
services:
  fleetbot-ircon:
    build: fleetbot-ircon
    image: monestri/iridium-fleetbot-ircon
    networks:
      - default
    volumes:
      - data:/bot
      - ./admins.json:/etc/botconfig/admins.json
      - ./botconfig.json:/etc/botconfig/botconfig.json
    restart: unless-stopped

networks:
  default:

volumes:
  data:
