version: "3.3"
services:
  fleetbot:
    build: fleetbot
    image: monestri/iridium-fleetbot:latest
    networks:
      - default
    volumes:
      - data:/bot
      - ./admins.json:/admins.json
      - ./botconfig.json:/botconfig.json
    restart: unless-stopped

  fleetbot-ircon:
    build: fleetbot-ircon
    image: monestri/iridium-fleetbot-ircon
    networks:
      - default
    volumes:
      - data:/bot
      - ./admins.json:/admins.json
      - ./botconfig.json:/botconfig.json
    restart: unless-stopped

  dev-tools:
    build: devtools
    image: monestri/dev-tools

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  default:

volumes:
  data:
