apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetbot-deployment
  labels:
    app: fleetbot
spec:
  selector:
    matchLabels:
      app: fleetbot
  replicas: 1
  template:
    metadata:
      labels:
        app: fleetbot
    spec:
      volumes:
        - name: bot-pv-storage
          persistentVolumeClaim:
            claimName: bot-pv-claim
        - name: secret-volume
          secret:
            secretName: bot-config
      containers:
        - name: fleetbot
          image: monestri/iridium-fleetbot-ircon:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/bot"
              name: bot-pv-storage
            - name: secret-volume
              mountPath: "/etc/botconfig"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bot-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/mnt/bot-data"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bot-pv-claim
spec:
  storageClassName: manual
  volumeName: bot-pv-volume
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
